on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - id: get_version
        uses: battila7/get-version-action@90eb8fc70f6dfcf3f9b95ed8f164d2c05038e729

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }}

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }} --no-build --output .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: nuget
          path: DanTheMan827.OnDeviceADB.${{ steps.get_version.outputs.version-without-v }}.nupkg

      - name: Push
        run: dotnet nuget push DanTheMan827.OnDeviceADB.${{ steps.get_version.outputs.version-without-v }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
